<a href="https://colab.research.google.com/github/saniaelizabath/Books-Python/blob/main/num.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [23]:
import numpy as np
arr=np.array([2,3,4])
print(arr)
list_of_lists=[[2,4,3],[2,4,7],[0,8,7]]
matrix=np.array(list_of_lists)
print(matrix)
np.arange(1,8)
np.arange(20)
np.ones(10)




[2 3 4]
[[2 4 3]
 [2 4 7]
 [0 8 7]]


array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [24]:
np.arange(1,888,40)

array([  1,  41,  81, 121, 161, 201, 241, 281, 321, 361, 401, 441, 481,
       521, 561, 601, 641, 681, 721, 761, 801, 841, 881])

In [27]:
np.zeros((2,10),int)

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

In [31]:
np.linspace(0,10,9)

array([ 0.  ,  1.25,  2.5 ,  3.75,  5.  ,  6.25,  7.5 ,  8.75, 10.  ])

In [34]:
np.eye(9)

array([[1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1.]])

In [35]:
np.random.rand(4,9)

array([[0.05816482, 0.20873812, 0.5695558 , 0.95071503, 0.16284263,
        0.03672893, 0.02010912, 0.29314291, 0.17419854],
       [0.34772397, 0.46825901, 0.82356378, 0.83853491, 0.41490191,
        0.73143832, 0.02474775, 0.41129324, 0.47682064],
       [0.83072785, 0.98341348, 0.21444689, 0.14941833, 0.35165427,
        0.7535299 , 0.24509758, 0.80422146, 0.16746227],
       [0.19641985, 0.3309086 , 0.86494767, 0.13798486, 0.73680712,
        0.52662918, 0.72453947, 0.25577199, 0.62098656]])

In [37]:
np.random.randn(3,2)

array([[-1.40155388, -0.76630138],
       [-0.22439215, -0.64742798],
       [-0.03769529, -0.22003211]])

In [40]:
np.random.randint(2,9)

3

In [41]:
np.random.randint(0,100,20)

array([ 3, 35, 52, 83, 73, 28, 81, 11, 16, 53, 94, 35, 97, 62, 35,  9, 17,
       53, 56, 56])

In [42]:
sample_array=np.arange(30)

In [43]:
rand_array=np.random.randint(0,100,20)

In [44]:
sample_array.reshape(3,10)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29]])

In [45]:
sample_array=np.arange(10,21)

In [46]:
sample_array[3]

13

In [47]:
sample_array[3:7]

array([13, 14, 15, 16])

In [48]:
sample_array[1:4]=100
print(sample_array)

[ 10 100 100 100  14  15  16  17  18  19  20]


In [49]:
subset_sample_array=sample_array[0:7]
print(subset_sample_array)

[ 10 100 100 100  14  15  16]


In [50]:
subset_sample_array[:]=100
print(subset_sample_array)

[100 100 100 100 100 100 100]


In [52]:
matrix=np.array([[5,4,3,3],[3,4,2,2],[3,8,9,4]])

In [54]:
matrix[0:2,2]


array([3, 2])

In [55]:
matrix[2,:]

array([3, 8, 9, 4])

In [56]:
matrix[2]

array([3, 8, 9, 4])

In [58]:
matrix[:,(2,0)]

array([[3, 5],
       [2, 3],
       [9, 3]])

In [59]:
sa=np.arange(1,20)

In [60]:
sa+sa

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34,
       36, 38])

In [61]:
np.exp(sa)

array([2.71828183e+00, 7.38905610e+00, 2.00855369e+01, 5.45981500e+01,
       1.48413159e+02, 4.03428793e+02, 1.09663316e+03, 2.98095799e+03,
       8.10308393e+03, 2.20264658e+04, 5.98741417e+04, 1.62754791e+05,
       4.42413392e+05, 1.20260428e+06, 3.26901737e+06, 8.88611052e+06,
       2.41549528e+07, 6.56599691e+07, 1.78482301e+08])

In [62]:
np.sqrt(sa)

array([1.        , 1.41421356, 1.73205081, 2.        , 2.23606798,
       2.44948974, 2.64575131, 2.82842712, 3.        , 3.16227766,
       3.31662479, 3.46410162, 3.60555128, 3.74165739, 3.87298335,
       4.        , 4.12310563, 4.24264069, 4.35889894])

In [63]:
np.std(sa)

5.477225575051661

In [65]:
np.log(sa)

array([0.        , 0.69314718, 1.09861229, 1.38629436, 1.60943791,
       1.79175947, 1.94591015, 2.07944154, 2.19722458, 2.30258509,
       2.39789527, 2.48490665, 2.56494936, 2.63905733, 2.7080502 ,
       2.77258872, 2.83321334, 2.89037176, 2.94443898])

In [66]:
np.max(sa)

19

In [67]:
np.min(sa)

1

In [69]:
np.argmax(sa)

18

In [70]:
np.argmin(sa)

0

In [71]:
np.square(sa)

array([  1,   4,   9,  16,  25,  36,  49,  64,  81, 100, 121, 144, 169,
       196, 225, 256, 289, 324, 361])

In [72]:
np.var(sa)

30.0

In [73]:
np.mean(sa)

10.0

In [74]:
ar=np.random.randn(3,4)

In [75]:
np.round(ar,decimals=3)

array([[ 1.293, -0.633, -0.502, -1.17 ],
       [ 1.094,  0.552,  1.026,  1.718],
       [ 1.068, -0.409, -0.645, -0.195]])

In [78]:
sports=np.array(['golf','cricket','fball','golf'])
np.unique(sports)

array(['cricket', 'fball', 'golf'], dtype='<U7')